### PR TITLE
TA06-033 Do not emit a warning 'multiple projects' too early

### PR DESCRIPTION
**Pull request by setton**
Emit this warning only once we have received didChangeConfiguration
and the project is still ambiguous at that point.

### CODE REVIEW

**Review by reznikmm — COMMENTED** [review]
How do you get this warning?

As for me this is important to let users know that ALS is unable to find a right project.

**Comment by setton** [comment]
> How do you get this warning?
> 
> As for me this is important to let users know that ALS is unable to find a right project.

The warning appears if didChangeConfiguration arrives and no project was specified.

**Comment by reznikmm** [comment]
But GNAT Studio *must* send the project in didChangeConfiguration, right? So this should be fixed on GNAT Studio side, I guess.

**Comment by setton** [comment]
> But GNAT Studio _must_ send the project in didChangeConfiguration, right? So this should be fixed on GNAT Studio side, I guess.

I'm not sure I follow... GNAT Studio is always working on a .gpr, so it always passes a .gpr to the ALS: there is never a reason to warn about "multiple projects found" for GNAT Studio. This needs to be sent to users of VScode who have not specified a project: if the ALS cannot find a project by the time didChangeConfiguration completes, then a message is sent back to VS Code.

**Comment by setton** [comment]
In other words, this fixes a bug whereby users of GNAT Studio were notified of "multiple projects" even though they shouldn't.

**Pull request closed without merging**
