### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by Entomy**
This fixes the out-of-order issue that was created with the `repository`. It seems like because the previous fixes were part of a different PR with other things going on at the same time, git failed to merge correctly and wound up with duplicate entries, as well as entries in unintended places. Everything was correct and still worked, this is just code cleanliness improvements.

### CODE REVIEW

**Comment by gcluzel** [comment]
> Everything was correct

I'm not as positive. 
image
Here is a bug introduced when I add `procedure_call_statement`. The affectation is not correctly highlighted.

**Comment by Entomy** [comment]
Hmm, okay. Looks like I need another test case in my sources.

**Comment by Entomy** [comment]
I'm gonna hold off on this until we finish the discussion at #436

**Comment by setton** [comment]
@Entomy there is something in your workflow (I think!) that git does not like and that results in the creation of the "merge" commits. Could you try

    git pull --rebase origin master
    git push -f 

to see if this works better?

**Comment by Entomy** [comment]
image

I feel like that didn't do anything.

My fork is ahead by several commits, and has been for a few PRs, even though those commits have already been merged into upstream. Absolutely no idea how that's happened, since I don't think I've done anything different. I've had a lot of problems with git that I haven't had with fossil or monotone, so I generally chock it up to clashes between my workflow and the intended workflow of git; we don't get along.

**Comment by gcluzel** [comment]
@Entomy Since you only have a single commit with your code, the simplest is probably the following commands:
```
$ git checkout Reorganization
$ git fetch upstream
$ git reset --hard upstream/master
$ git cherry-pick 2f2a392aa24fc7c8a9e36b476703fef3108944f4
```
I assumed that `upstream` is the name of the AdaCore's remote repository.
Once you've done this you should have something like that:
```
$ git log --oneline 
e069656 (HEAD -> Reorganization) Fixed out-of-order alphabetical organization
9af83c5 (upstream/master) Add regression test for code nesting
b8e8902 Missing use clause in the client
50a57fc T414-024 Generate Write for more types
1171945 T414-024 Expcicitly specify writting of empty arrays
...
```
And then `git push -f` to update your remote branch.

**Comment by Entomy** [comment]
Well it's a good thing someone has a good understanding of git because I sure have no idea what those commands did 🤣

**Pull request merged**
