### PR TITLE
Merging Projects

### PR DESCRIPTION
**Pull request by Entomy**
**Don't merge this yet**

I'm opening the PR now to allow for individual components to be assessed and merged/rejected much easier than if the entire thing was done all at once. There's several conflicting files, such as the ada/gpr definitions, but also several new files, and different naming schemes for things, that will all need to be addressed.

As stated in #309, part of why I'm doing this is that I simply can't continue to use VS Code given how parts of a disability has progressed, and how the VS Code team doesn't seem interested in a solution, which is insane because I know I'm not the only person troubled by use of a mouse.

The files I'm merging are from the last state of the repo that made it up on the marketplace. I've worked out better solutions for the overall approach and organization, and have partially implemented that work. I can continue to try to work on them in the future, but I also have no issue sharing that knowledge if someone else feels like taking a stab at it or helping.

### CODE REVIEW

**Comment by Entomy** [comment]
That one's got what I've worked out of the `.ali` syntax. It's limited, but provides some highlighting.

**Comment by Entomy** [comment]
Well, you guys already have my `.gpr` syntax 😂. Thanks for fixing the inconsistent whitespace from before I added an `.editorconfig`

**Comment by setton** [comment]
@Entomy thank you for this! Waiting for your green light before we review/merge.

(@dgautherot you forgot to credit @Entomy for `gpr.tmLanguage.json` if you had imported it from his repository :-))

**Comment by Entomy** [comment]
@setton legally speaking, he's fine and actually didn't need to in this instance. I released that code in the public domain. He owns it just as much as I do.

@dgautherot you still should as a "cover your ass" decision 😉

**Comment by Entomy** [comment]
@setton 🟢

**Comment by setton** [comment]
Thanks a lot for this! This all looks good to me, but I'm not an expert, I would like @reznikmm to have a look as well, since he knows the VScode integration better.

**Comment by Entomy** [comment]
> Well, you guys already have my .gpr syntax 😂.

Since this is inevitably one of the dangerous sides of OSS development, [Codequiry](https://codequiry.com/) may be useful. It's derived from [MOSS](https://theory.stanford.edu/~aiken/moss/) and checks against some online sources as well. Although it's still primarily meant for academic situations, they do list use cases for outsourcing and code infringement claims.

**Comment by Entomy** [comment]
I'll add some closing remarks so everyone's on the same page.

With regards to language support, a large portion of Ada syntax, definitely most things people use, is supported. This should include your **gnatdoc** comments as well, albeit only simply, and iirc, your convention of comment boxes above subroutines (I used them as section markers, but the syntax is the same). Jere has pointed out a few cases where little to no highlighting occurs. Iirc record layout clauses are one of them. I delayed this for these rewrite.

The syntax files are severely nested. When I was writing the extension initially this was allowed by the schema. This is still legal, but discouraged, now. Unnesting this is probably the best starting point towards refining them.

VS Code's classifier operates on a line by line basis, using an implementation of Oniguruma Regex. As such, allowing line breaks inside of syntax elements becomes interesting. The existing implementation is spotty, but does conform to most common style conventions. Through clever use of `begin` and `end`, along with lookarounds, you can get it to allow line breaks at _almost_ every keyword, identifier, and delimiter boundary. I've done some of the initial work there, to prove it works, at least. 

With regards to theme, as I developed the extension I did test against the built in themes, but also developed my own theme [Ofbase](https://marketplace.visualstudio.com/items?itemName=Entomy.offbase), which supports the more fine grained highlighting that benefits keyword heavy languages like Ada. Default themes work fine regardless, although I do find Microsoft's themes "Light+/Dark+" do make the bad assumption that intrinsic types are keywords, and are themed the same way, so those specific themes can cause entire lines to look like keywords. If you check TM Scope you can see it's a theme oddity, but user assumption may be extension error. Going forward it may be a good idea to slightly violate convention and classify all types as `support.type` regardless, rather than `storage.type`.

**Comment by setton** [comment]
Thank you for the valuable insights! Hope VS Code won’t forbid nesting before we have had time to unnest.

**Comment by setton** [comment]
And thank you for the valuable contributions @Entomy!

**Pull request merged**
