### PR TITLE
Add aspect_clause support

### PR DESCRIPTION
**Pull request by gcluzel**
I have added a partial support for the syntax highlighting of `aspect_clause`s.

**Limitations**:

- The support is not complete. The `at_clause` construction is not supported by this work (cf. [here](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-13-1.html#I4417)) because I'm not enough familiar with Ada to know how it is used.

- Moreover, in the following construction, I don't know what scope I should give to `attribute_designator` in `for local_name'attribute_designator use expression;`. Then no scope is assigned to it.

### CODE REVIEW

**Comment by gcluzel** [comment]
I'd like to have your opinion @Entomy about the way I parse aspect_clause and component_clause in commit ce4562a. I think it's better because lines can be broken everywhere, but I'd like to know what you think about that.

**Comment by Entomy** [comment]
`enumeration_representation_clause` looks good.

`component_clause` should be using:

~~~~ javascript
"beginCaptures": {
    "2": { "name": "storage.modifier.ada" },
},
~~~~

In this context, `at` is specifying a field offset, which modifies the type, so that's more precise about the meaning.

As far as the changes to `aspect_clause` go:

~~~~ javascript
{
    "begin": "(?i)(?<=for)",
    "end": "(?i)(?=use)",
    "captures": {
        "0": { "name": "keyword.ada" }
    },
    "patterns": [
        {
            "match": "((?:\\w|\\d|_)+)(?:(\\')((?:\\w|\\d|_)+))?",
            "captures": {
                "1": { "patterns": [ { "include": "#subtype_mark" } ] },
                "2": { "name": "punctuation.ada" },
                "3": { "name": "entity.other.attribute-name.ada" } // Add this
            }
        }
    ]
}
~~~~

> The support is not complete. The at_clause construction is not supported by this work (cf. here) because I'm not enough familiar with Ada to know how it is used.

Improvements don't need to get every construct flawless from the first commit. We'll get there.

**Comment by gcluzel** [comment]
Thank you @Entomy  for these improvements. I have corrected them

**Comment by Entomy** [comment]
Awesome, thanks!

I can't check this until tomorrow.

**Comment by Entomy** [comment]
I don't have the test sources I've been using here, but I put something together. Looks good to me!

**Pull request merged**
